## Synthetic population pipeline for Sao-Paulo
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: /nas/balacm/SaoPauloSynPP/cache_test

# This section defines which parts of the pipeline should be run
run:
  #- data.census.raw
  #- data.spatial.zones
  #- data.hts.cleaned
  #- synthesis.population.trips
  #- synthesis.population.spatial.by_person.primary_zones
  #- synthesis.population.spatial.by_person.primary_locations
  #- synthesis.population.spatial.by_person.secondary.locations
  #- synthesis.output # To create the output population in the output_path (see below)
  #- synthesis.population.spatial.locations
  #- synthesis.population.activities
  #- matsim.scenario.population
  #- matsim.scenario.supply.processed
  #- matsim.scenario.supply.osm
  - matsim.runtime.eqasim
  - matsim.output # Uncomment, if you want to run the full simulation (you'll need Java for that)
  #- analysis.analysis

# Here the configuraiton of the pipeline starts
config:
  # Some general configuration
  processes: 24

  # Define sampling rate and random seed for the output population
  sampling_rate: 0.01
  random_seed: 1234

  # Paths to the input data and where the output should be stored
  data_path: /nas/balacm/Data_SP
  output_path: /nas/balacm/SaoPauloSynPP/output

  shapefile_name: "SC2010_RMSP_CEM_V3_all_state.shp"
  shapefile_center_name: "SC2010_RMSP_CEM_V3_center.shp"
  shapefile_city_name: "SC2010_RMSP_CEM_V3_city.shp"
  census_file: "Censo.2010.brasil.amostra.10porcento.sav"
  osm_file: "sao_paulo.osm.pbf"
  osm_matsim_file: "sao_paulo.osm.gz"
  hts_file: "OD_2017.dbf"

  # Only interesting if you run the simulation
  java_memory: 80G

  # Only interesting if the analysis script is run
  analysis_path: /nas/balacm/SaoPauloSynPP/Analysis
